using Hrithik.Security.RequestSigning.Abstractions;
using Hrithik.Security.RequestSigning.Canonicalization;
using Hrithik.Security.RequestSigning.Crypto;
using Hrithik.Security.RequestSigning.Exceptions;
using Hrithik.Security.RequestSigning.Options;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;

namespace Hrithik.Security.RequestSigning.Middleware
{
    /// <summary>
    /// ASP.NET Core middleware that validates incoming HTTP requests
    /// using HMAC-based request signing.
    /// </summary>
    /// <remarks>
    /// The middleware enforces request integrity, authenticity, and
    /// replay-attack protection by validating a cryptographic signature
    /// generated by the client.
    ///
    /// Requests must include the required signing headers such as
    /// client identifier, nonce, timestamp, and signature.
    /// </remarks>
    public sealed class RequestSigningMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly RequestSigningOptions _options;
        private readonly ISigningKeyProvider _keyProvider;

        /// <summary>
        /// Initializes a new instance of the <see cref="RequestSigningMiddleware"/> class.
        /// </summary>
        /// <param name="next">
        /// The next middleware delegate in the HTTP request pipeline.
        /// </param>
        /// <param name="options">
        /// The request signing configuration options.
        /// </param>
        /// <param name="keyProvider">
        /// A provider responsible for resolving signing secrets
        /// for incoming client identifiers.
        /// </param>
        public RequestSigningMiddleware(
            RequestDelegate next,
            IOptions<RequestSigningOptions> options,
            ISigningKeyProvider keyProvider)
        {
            _next = next;
            _options = options.Value;
            _keyProvider = keyProvider;
        }

        /// <summary>
        /// Processes the HTTP request and validates its signature.
        /// </summary>
        /// <param name="context">The current HTTP context.</param>
        /// <returns>
        /// A task that represents the asynchronous middleware operation.
        /// </returns>
        /// <exception cref="InvalidSignatureException">
        /// Thrown when the request is missing required headers,
        /// contains an invalid timestamp, or fails signature verification.
        /// </exception>
        public async Task InvokeAsync(HttpContext context)
        {
            // Skip signing validation for safe, idempotent GET requests
            if (HttpMethods.IsGet(context.Request.Method))
            {
                await _next(context);
                return;
            }

            // Validate presence of required signing headers
            if (!context.Request.Headers.TryGetValue(_options.ClientIdHeader, out var clientId) ||
                !context.Request.Headers.TryGetValue(_options.NonceHeader, out var nonce) ||
                !context.Request.Headers.TryGetValue(_options.TimestampHeader, out var timestamp) ||
                !context.Request.Headers.TryGetValue(_options.SignatureHeader, out var signature))
            {
                throw new InvalidSignatureException(
                    "Missing request signing headers.",
                    "RS-001");
            }

            // Validate timestamp format
            if (!long.TryParse(timestamp, out var epoch))
            {
                throw new InvalidSignatureException(
                    "Invalid timestamp.",
                    "RS-002");
            }

            // Validate timestamp skew
            var requestTime = DateTimeOffset.FromUnixTimeSeconds(epoch);
            if (Math.Abs((DateTimeOffset.UtcNow - requestTime).TotalSeconds) >
                _options.AllowedClockSkew.TotalSeconds)
            {
                throw new InvalidSignatureException(
                    "Request timestamp outside allowed clock skew.",
                    "RS-003");
            }

            // Resolve client signing secret
            var secret = await _keyProvider.GetSecretAsync(clientId!);
            if (secret == null)
            {
                throw new InvalidSignatureException(
                    "Unknown client.",
                    "RS-004",
                    StatusCodes.Status403Forbidden);
            }

            // Build canonical request representation
            var canonical = await CanonicalRequestBuilder.BuildAsync(
                context,
                clientId!,
                nonce!,
                timestamp!);

            // Verify request signature
            if (!HmacSha256Signer.Verify(canonical, secret, signature!))
            {
                throw new InvalidSignatureException(
                    "Invalid request signature.",
                    "RS-005",
                    StatusCodes.Status401Unauthorized);
            }

            // Continue pipeline if validation succeeds
            await _next(context);
        }
    }
}
